stages:
  - audit

variables:
  GIT_SUBMODULE_STRATEGY: recursive

audit_job:
  stage: audit
  script:
    - ./workflows/pre-commit/quick-audit.sh "$CI_PROJECT_DIR"
  only:
    - merge_requests

notify:
  stage: audit
  when: always
  script:
    - if [ -n "$SLACK_WEBHOOK" ]; then curl -X POST -H 'Content-type: application/json' --data '{"text":"GitLab audit completed for $CI_PROJECT_PATH"}' "$SLACK_WEBHOOK"; fi
  dependencies:
    - audit_job
