name: Quarterly Architecture Review

on:
  schedule:
    - cron: '0 7 1 1,4,7,10 *'

jobs:
  architecture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run quick audit
        run: |
          ./workflows/pre-commit/quick-audit.sh "${{ github.workspace }}"
      - name: Archive report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: architecture-report
          path: /tmp/quick-audit.json
