name: Weekly Security Scan

on:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run security check
        run: |
          ./workflows/pre-commit/security-check.sh "${{ github.workspace }}"
      - name: Open issue with results
        if: always()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: 'Weekly Security Scan Results'
          content-filepath: /tmp/security-report.json
          labels: security
